name: 04 - Env and Secrets
on:
  push:
    branches:
      - main

# Global environment variables
env:
  APP_NAME: sample-app
  ENVIRONMENT: dev

jobs:
  env-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment variables
        run: |
          echo "App Name: $APP_NAME"
          echo "Environment: $ENVIRONMENT"

      - name: Use secret (masked in logs)
        run: echo "Deploying with secret key"
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}

########## about this file ##############

#üß† Learned concepts
#Global env
#Step-level env
#GitHub Secrets usage
#Secrets are masked in logs
#‚ö†Ô∏è Add secret in:
#Repo ‚Üí Settings ‚Üí Secrets ‚Üí Actions